-- 26. Query to display Name and Employee no. Along with their supervisor’s Name and the supervisor’s employee no; along with the Employees’ Name who do not have a supervisor.
-- 27. Query to display Name, Dept No. And Salary of any employee whose departement No. and salary matches both the departement no. And the salary of any employee who earns a commission. 
-- 32. Query to display the departement Name, Location Name, No. of Employees and the average salary for all employees in that departement.
-- 35. Query to display Employee Number and Name for all employees who work in a departement with any employee whose name contains a ‘T’. 
-- 36. Query to display the names and salaries of all employees who report to supervisor named ‘King’.
-- 41. Query to find the employee’ name who is not supervisor and name of supervisor supervising more than 5 employees.
-- 42. Query to display the job type with maximum and minimum employees.